version: '3'
services:

  api:
    container_name: API
    build:
      context: .
    links:
      - redis
      - mongodb
    environment:
      - NODE_ENV=docker
    env_file:
      - .env
    ports:
      - 9000:9000

  redis:
    image: redis:alpine
    container_name: Cache
    command: redis-server --appendonly no --save ''
    ports:
      - 6379:6379    

  mongodb:
    image : mongo
    container_name: Database
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /tmp/mongo:/data/db
    ports:
      - 27017:27017
